strategy: MovingAverageCrossStrategy
cash: 500000.00
tickers:
  - AMZN
  - AAPL
  #- 600000
benchmark:            # or leave it empty
start_date: 2010-Jan-01
end_date: 2017-May-01
datasource: quandl   # local, quandl
hist_dir: d:/workspace/elitequant_matlab/hist
output_dir: d:/workspace/elitequant_matlab/out